Repository redBorder/cookbook-rb-monitor, pull requests merged in 2024-06, with the labels that each got.

#12 Bugfix/17260 wrong configuration monitor services
  resources/libraries/update_manager_config.rb
Labels: size/M, kind/bug

#13 Release 0.0.5
  .github/workflows/rpm.yml
  CHANGELOG.md
  README.md
  resources/libraries/update_manager_config.rb
  resources/metadata.rb
Labels: size/L, kind/documentation

#14 Change rb_http_mode to Normal
  resources/libraries/rbmonitor_helpers.rb
Labels: kind/bug, size/XS

#15 Release 0.0.6
  CHANGELOG.md
  resources/libraries/rbmonitor_helpers.rb
  resources/metadata.rb
Labels: kind/documentation, size/XS

#16 Bugfix/1764 service values being overwritten in node
  resources/libraries/update_manager_config.rb
Labels: size/XS

#17 Release 0.0.7
  CHANGELOG.md
  resources/libraries/update_manager_config.rb
  resources/metadata.rb
Labels: bug, size/S, kind/bug, release

#18 Improvement/fix lint
  resources/attributes/default.rb
  resources/libraries/rbmonitor_helpers.rb
  resources/libraries/update_cluster_config.rb
  resources/libraries/update_manager_config.rb
  resources/libraries/update_sensor_config.rb
  resources/libraries/update_service_config.rb
  resources/providers/config.rb
  resources/recipes/default.rb
  resources/resources/config.rb
Labels: enhancement, kind/bug, lint, refactor, size/XL

#19 Release 0.0.8
  CHANGELOG.md
  resources/attributes/default.rb
  resources/libraries/rbmonitor_helpers.rb
  resources/libraries/update_cluster_config.rb
  resources/libraries/update_manager_config.rb
  resources/libraries/update_sensor_config.rb
  resources/libraries/update_service_config.rb
  resources/metadata.rb
  resources/providers/config.rb
  resources/recipes/default.rb
  resources/resources/config.rb
Labels: kind/documentation, size/XL
